### ISSUE TITLE
Project TODO

### ISSUE THREAD

**Issue by comaldave** [davsk/WebDev#9]
- [ ] Fork Template
- [ ] Setup Davsk.com 
- [ ] Setup Davsk.net
- [ ] Setup 5tribes.org
- [ ] Setup ReplayRLB.com Netlify manages subdomains.
- [ ] Update Wiki
